# Generated by Django 5.0.2 on 2024-06-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butik_icerik', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butik_icerik.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
