# Generated by Django 5.0.2 on 2024-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butik_icerik', '0003_banner2_delete_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner2',
            new_name='Banner',
        ),
    ]
